Document: mfreq
Title: Debian mfreq Manual
Author: <insert document author here>
Abstract: This manual describes what mfreq is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mfreq/mfreq.sgml.gz

Format: postscript
Files: /usr/share/doc/mfreq/mfreq.ps.gz

Format: text
Files: /usr/share/doc/mfreq/mfreq.text.gz

Format: HTML
Index: /usr/share/doc/mfreq/html/index.html
Files: /usr/share/doc/mfreq/html/*.html
